#!/bin/bash

persion1=sachi
persion2=mithun
echo "$persion1 :: hi $persion2 how r u"
echo "$persion2 :: hello $persion1 i am good"
echo "$persion1 :: $persion2 good morning bro"  
echo "$persion2 :: V V GM $persion1 tq!!!"