#!/bin/bash

persion1=shiva
persion2=harii

echo "$persion1 :: hi $persion2 when did u came"
echo "$persion2 :: hello $persion1 just now in bus man "
echo "$persion1 :: ok fine $persion2 did u complete ur lunch "
echo "$persion2 :: ha ha haaa $persion1 still no man, "